net send OSIPOV-G "B2 code freeze"
net send MALKOVSKIY-A "B2 code freeze"
net send SMIRNOV-A "B2 code freeze"
net send VESELOV-A "B2 code freeze"
net send BALASHOV-A "B2 code freeze"
net send GALATA-A "B2 code freeze"
net send UVARKOV-D "B2 code freeze"
net send CHELUBEEV-I "B2 code freeze"
net send OGORODOV-I "B2 code freeze"
net send MELNIKOV-M "B2 code freeze"
net send KABANOV-N "B2 code freeze"
net send OVECHKIN-O "B2 code freeze"
net send ZHIKHOR-V "B2 code freeze"
net send BEROV-V "B2 code freeze"
net send BLAZHEVICHY "B2 code freeze"
net send ANDY "B2 code freeze"

