menu01_on = new Image();  menu01_off = new Image(); 
menu01_on.src = "http://www.warheroes.ru/img/menu01_on.gif"; menu01_off.src =  "http://www.warheroes.ru/img/menu01_off.gif";
menu02_on = new Image();  menu02_off = new Image(); 
menu02_on.src = "http://www.warheroes.ru/img/menu02_on.gif"; menu02_off.src =  "http://www.warheroes.ru/img/menu02_off.gif";
menu03_on = new Image();  menu03_off = new Image(); 
menu03_on.src = "http://www.warheroes.ru/img/menu03_on.gif"; menu03_off.src =  "http://www.warheroes.ru/img/menu03_off.gif";
menu04_on = new Image();  menu04_off = new Image(); 
menu04_on.src = "http://www.warheroes.ru/img/menu04_on.gif"; menu04_off.src =  "http://www.warheroes.ru/img/menu04_off.gif";
menu05_on = new Image();  menu05_off = new Image(); 
menu05_on.src = "http://www.warheroes.ru/img/menu05_on.gif"; menu05_off.src =  "http://www.warheroes.ru/img/menu05_off.gif";
menu07_on = new Image();  menu07_off = new Image(); 
menu07_on.src = "http://www.warheroes.ru/img/menu07_on.gif"; menu07_off.src =  "http://www.warheroes.ru/img/menu07_off.gif";
menu06_on = new Image();  menu06_off = new Image(); 
menu06_on.src = "http://www.warheroes.ru/img/menu06_on.gif"; menu06_off.src =  "http://www.warheroes.ru/img/menu06_off.gif";

    l0=new Image();  lb0=new Image(); l0.src = "http://www.warheroes.ru/img/l0.gif";	lb0.src = "http://www.warheroes.ru/img/lb0.gif";
    l1=new Image();  lb1=new Image(); l1.src = "http://www.warheroes.ru/img/l1.gif";	lb1.src = "http://www.warheroes.ru/img/lb1.gif";
    l2=new Image();  lb2=new Image(); l2.src = "http://www.warheroes.ru/img/l2.gif";	lb2.src = "http://www.warheroes.ru/img/lb2.gif";
    l3=new Image();  lb3=new Image(); l3.src = "http://www.warheroes.ru/img/l3.gif";	lb3.src = "http://www.warheroes.ru/img/lb3.gif";
    l4=new Image();  lb4=new Image(); l4.src = "http://www.warheroes.ru/img/l4.gif";	lb4.src = "http://www.warheroes.ru/img/lb4.gif";
    l5=new Image();  lb5=new Image(); l5.src = "http://www.warheroes.ru/img/l5.gif";	lb5.src = "http://www.warheroes.ru/img/lb5.gif";
    l6=new Image();  lb6=new Image(); l6.src = "http://www.warheroes.ru/img/l6.gif";	lb6.src = "http://www.warheroes.ru/img/lb6.gif";
    l7=new Image();  lb7=new Image(); l7.src = "http://www.warheroes.ru/img/l7.gif";	lb7.src = "http://www.warheroes.ru/img/lb7.gif";
    l8=new Image();  lb8=new Image(); l8.src = "http://www.warheroes.ru/img/l8.gif";	lb8.src = "http://www.warheroes.ru/img/lb8.gif";
    l9=new Image();  lb9=new Image(); l9.src = "http://www.warheroes.ru/img/l9.gif";	lb9.src = "http://www.warheroes.ru/img/lb9.gif";
    l10=new Image();  lb10=new Image(); l10.src = "http://www.warheroes.ru/img/l10.gif";	lb10.src = "http://www.warheroes.ru/img/lb10.gif";
    l11=new Image();  lb11=new Image(); l11.src = "http://www.warheroes.ru/img/l11.gif";	lb11.src = "http://www.warheroes.ru/img/lb11.gif";
    l12=new Image();  lb12=new Image(); l12.src = "http://www.warheroes.ru/img/l12.gif";	lb12.src = "http://www.warheroes.ru/img/lb12.gif";
    l13=new Image();  lb13=new Image(); l13.src = "http://www.warheroes.ru/img/l13.gif";	lb13.src = "http://www.warheroes.ru/img/lb13.gif";
    l14=new Image();  lb14=new Image(); l14.src = "http://www.warheroes.ru/img/l14.gif";	lb14.src = "http://www.warheroes.ru/img/lb14.gif";
    l15=new Image();  lb15=new Image(); l15.src = "http://www.warheroes.ru/img/l15.gif";	lb15.src = "http://www.warheroes.ru/img/lb15.gif";
    l16=new Image();  lb16=new Image(); l16.src = "http://www.warheroes.ru/img/l16.gif";	lb16.src = "http://www.warheroes.ru/img/lb16.gif";
    l17=new Image();  lb17=new Image(); l17.src = "http://www.warheroes.ru/img/l17.gif";	lb17.src = "http://www.warheroes.ru/img/lb17.gif";
    l18=new Image();  lb18=new Image(); l18.src = "http://www.warheroes.ru/img/l18.gif";	lb18.src = "http://www.warheroes.ru/img/lb18.gif";
    l19=new Image();  lb19=new Image(); l19.src = "http://www.warheroes.ru/img/l19.gif";	lb19.src = "http://www.warheroes.ru/img/lb19.gif";
    l20=new Image();  lb20=new Image(); l20.src = "http://www.warheroes.ru/img/l20.gif";	lb20.src = "http://www.warheroes.ru/img/lb20.gif";
    l21=new Image();  lb21=new Image(); l21.src = "http://www.warheroes.ru/img/l21.gif";	lb21.src = "http://www.warheroes.ru/img/lb21.gif";
    l22=new Image();  lb22=new Image(); l22.src = "http://www.warheroes.ru/img/l22.gif";	lb22.src = "http://www.warheroes.ru/img/lb22.gif";
    l23=new Image();  lb23=new Image(); l23.src = "http://www.warheroes.ru/img/l23.gif";	lb23.src = "http://www.warheroes.ru/img/lb23.gif";
    l24=new Image();  lb24=new Image(); l24.src = "http://www.warheroes.ru/img/l24.gif";	lb24.src = "http://www.warheroes.ru/img/lb24.gif";
    l25=new Image();  lb25=new Image(); l25.src = "http://www.warheroes.ru/img/l25.gif";	lb25.src = "http://www.warheroes.ru/img/lb25.gif";
    l26=new Image();  lb26=new Image(); l26.src = "http://www.warheroes.ru/img/l26.gif";	lb26.src = "http://www.warheroes.ru/img/lb26.gif";
    l27=new Image();  lb27=new Image(); l27.src = "http://www.warheroes.ru/img/l27.gif";	lb27.src = "http://www.warheroes.ru/img/lb27.gif";
    l28=new Image();  lb28=new Image(); l28.src = "http://www.warheroes.ru/img/l28.gif";	lb28.src = "http://www.warheroes.ru/img/lb28.gif";
    l29=new Image();  lb29=new Image(); l29.src = "http://www.warheroes.ru/img/l29.gif";	lb29.src = "http://www.warheroes.ru/img/lb29.gif";
    l30=new Image();  lb30=new Image(); l30.src = "http://www.warheroes.ru/img/l30.gif";	lb30.src = "http://www.warheroes.ru/img/lb30.gif";
      
menu_but_off = new Image();  menu_but_on = new Image();
menu_but_off.src = "http://www.warheroes.ru/img/menu_but_off.gif";  menu_but_on.src = "http://www.warheroes.ru/img/menu_but_on.gif"; 
menu_line_off = new Image(); menu_line_on = new Image(); 
menu_line_off.src = "http://www.warheroes.ru/img/menu_line_off.gif"; menu_line_on.src = "http://www.warheroes.ru/img/menu_line_on.gif";
