md A_Officer_w
md Artillery_gunner
md Assault_sapper_Bren_w
md Assault_sapper_flamethrower
md Assault_sapper_PIAT_w
md Assault_sapper_Sten_w
md AT_Gunner_Boisa
md AT_gunner_PIAT
md AT_gunner_PIAT_as
md Commando
md FlameThrower
md Gunner_Enfield
md M_gunner_Bren
md M_gunner_Bren_as
md Officer
md officer_as
md Officer_paratrooper
md Paratrooper
md Sapper
md SM_gunner_Sten
md Sniper
